# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe946c9f106171fd619816cc286749493dce06afb14c782edbf8f9daedb5f760e5a31cc9235f6767a80a05d00cfa9cfef8ecd4871c4b6de646629c05ca274139

test:
  secret_key_base: 95d88a9a22ae90b30cbaa51e774745991792a20372f762608a3067ab394cb0648c9565358df1b0ace0364e6eea33428a0e967b28cfa1b7139bc0dfd93a914854

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
